name: api_client
description: API client
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  app_core:
    path: ../app_core
  cloud_firestore: ^5.6.1
  cloud_functions: ^5.3.0
  firebase_analytics: ^11.4.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_storage: ^12.4.0
  flutter:
    sdk: flutter
  flutter_web_auth_2: ^4.1.0
  google_sign_in: ^6.2.2
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.2
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
