name: app_core
description: App core package
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^9.0.0
  collection: ^1.19.0
  equatable: ^2.0.7
  formz: ^0.8.0
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  slugify: ^2.0.0
  timezone: ^0.10.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^7.0.0
